# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/chunk.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/chunk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import net_pb2 as proto_dot_net__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/chunk.proto\x12\x08pblczero\x1a\x0fproto/net.proto\"\x83\x01\n\x05State\x12\x11\n\x05plane\x18\x01 \x03(\x06\x42\x02\x10\x01\x12\x0e\n\x06us_ooo\x18\x02 \x01(\r\x12\r\n\x05us_oo\x18\x03 \x01(\r\x12\x10\n\x08them_ooo\x18\x04 \x01(\r\x12\x0f\n\x07them_oo\x18\x05 \x01(\r\x12\x14\n\x0cside_to_move\x18\x06 \x01(\r\x12\x0f\n\x07rule_50\x18\x07 \x01(\r\".\n\x06Policy\x12\x11\n\x05index\x18\x01 \x03(\rB\x02\x10\x01\x12\x11\n\x05prior\x18\x02 \x03(\x02\x42\x02\x10\x01\"\xbe\x01\n\x04Game\x12\x1e\n\x05state\x18\x01 \x03(\x0b\x32\x0f.pblczero.State\x12 \n\x06policy\x18\x02 \x03(\x0b\x32\x10.pblczero.Policy\x12\x11\n\x05value\x18\x03 \x03(\x02\x42\x02\x10\x01\x12\x10\n\x04move\x18\x04 \x03(\rB\x02\x10\x01\x12%\n\x06result\x18\x05 \x01(\x0e\x32\x15.pblczero.Game.Result\"(\n\x06Result\x12\t\n\x05WHITE\x10\x00\x12\t\n\x05\x42LACK\x10\x01\x12\x08\n\x04\x44RAW\x10\x02\"o\n\x05\x43hunk\x12\r\n\x05magic\x18\x01 \x01(\x07\x12\x0f\n\x07license\x18\x02 \x01(\t\x12(\n\x07version\x18\x03 \x01(\x0b\x32\x17.pblczero.EngineVersion\x12\x1c\n\x04game\x18\x04 \x03(\x0b\x32\x0e.pblczero.Game')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.chunk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATE'].fields_by_name['plane']._loaded_options = None
  _globals['_STATE'].fields_by_name['plane']._serialized_options = b'\020\001'
  _globals['_POLICY'].fields_by_name['index']._loaded_options = None
  _globals['_POLICY'].fields_by_name['index']._serialized_options = b'\020\001'
  _globals['_POLICY'].fields_by_name['prior']._loaded_options = None
  _globals['_POLICY'].fields_by_name['prior']._serialized_options = b'\020\001'
  _globals['_GAME'].fields_by_name['value']._loaded_options = None
  _globals['_GAME'].fields_by_name['value']._serialized_options = b'\020\001'
  _globals['_GAME'].fields_by_name['move']._loaded_options = None
  _globals['_GAME'].fields_by_name['move']._serialized_options = b'\020\001'
  _globals['_STATE']._serialized_start=49
  _globals['_STATE']._serialized_end=180
  _globals['_POLICY']._serialized_start=182
  _globals['_POLICY']._serialized_end=228
  _globals['_GAME']._serialized_start=231
  _globals['_GAME']._serialized_end=421
  _globals['_GAME_RESULT']._serialized_start=381
  _globals['_GAME_RESULT']._serialized_end=421
  _globals['_CHUNK']._serialized_start=423
  _globals['_CHUNK']._serialized_end=534
# @@protoc_insertion_point(module_scope)
